# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWt < Formula
  desc "Agent-friendly git worktrees: pre-provisioned via copy-on-write, one naming convention"
  homepage "https://github.com/sonyabytes/git-wt"
  version "0.1.1"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonyabytes/git-wt/releases/download/v0.1.1/git-wt_0.1.1_darwin_amd64.tar.gz"
      sha256 "cea5a22f271c978a2fdcb5a5f8ee9c5901f3a17a4049836425477dc47abd5acb"

      define_method(:install) do
        bin.install "git-wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonyabytes/git-wt/releases/download/v0.1.1/git-wt_0.1.1_darwin_arm64.tar.gz"
      sha256 "81faf1352b2faf8bf4a23e7fa7eb2dda25f8999708eaf1d79e782d31a18d4a9c"

      define_method(:install) do
        bin.install "git-wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyabytes/git-wt/releases/download/v0.1.1/git-wt_0.1.1_linux_amd64.tar.gz"
      sha256 "1ad7d734569628d94fbcfd97de9cee36992f7643d6c039048158e6f055cf097c"
      define_method(:install) do
        bin.install "git-wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyabytes/git-wt/releases/download/v0.1.1/git-wt_0.1.1_linux_arm64.tar.gz"
      sha256 "121eca52c27eb0f5bf478a3408f73b92048fbce3ba531d0ace5ca1bf6ced7299"
      define_method(:install) do
        bin.install "git-wt"
      end
    end
  end

  test do
    system "#{bin}/git-wt", "--help"
  end
end
