# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitWt < Formula
  desc "Agent-friendly git worktrees: pre-provisioned via copy-on-write, one naming convention"
  homepage "https://github.com/sonyabytes/git-wt"
  version "0.1.3"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonyabytes/git-wt/releases/download/v0.1.3/git-wt_0.1.3_darwin_amd64.tar.gz"
      sha256 "541680821dcc16857641c18bdda50b75476063b7d3fb90dbab772800ddd86924"

      define_method(:install) do
        bin.install "git-wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonyabytes/git-wt/releases/download/v0.1.3/git-wt_0.1.3_darwin_arm64.tar.gz"
      sha256 "e7eec87daf804448c157dae394c2d66216e7bb76841085df69cf3670481182ed"

      define_method(:install) do
        bin.install "git-wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyabytes/git-wt/releases/download/v0.1.3/git-wt_0.1.3_linux_amd64.tar.gz"
      sha256 "754fbe38d1d8d547073daff3dbaff674fdc14839edb30fdc11a72f4629e10281"
      define_method(:install) do
        bin.install "git-wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyabytes/git-wt/releases/download/v0.1.3/git-wt_0.1.3_linux_arm64.tar.gz"
      sha256 "4f282bc8cc69b18d2a519a8e2b9e6e0d87ec51503fdf7ebe355ff5ae27168d9a"
      define_method(:install) do
        bin.install "git-wt"
      end
    end
  end

  test do
    system "#{bin}/git-wt", "--help"
  end
end
