# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wut < Formula
  desc "Route accidental natural-language shell input to your AI harness"
  homepage "https://github.com/sonyabytes/wut"
  version "0.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonyabytes/wut/releases/download/v0.6.4/wut_Darwin_x86_64.tar.gz"
      sha256 "f7a597a98beb2ddbc624e738d9ec50108d654cae2b3cbc43ba8e2d24910c3114"

      define_method(:install) do
        bin.install "wut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonyabytes/wut/releases/download/v0.6.4/wut_Darwin_arm64.tar.gz"
      sha256 "5c17199a09b969bf8dda59e9dca32c9ec7bcb39eadcdebfce7fe4526f5660274"

      define_method(:install) do
        bin.install "wut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyabytes/wut/releases/download/v0.6.4/wut_Linux_x86_64.tar.gz"
      sha256 "179da6eb1b0022fdc2dd8bce6d64ba71cf35c12067ff7e0ea628f631ed9dba60"
      define_method(:install) do
        bin.install "wut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyabytes/wut/releases/download/v0.6.4/wut_Linux_arm64.tar.gz"
      sha256 "4c745a8bb141db1572b7413983aeb34284f8ba11eec254e20970f86228179561"
      define_method(:install) do
        bin.install "wut"
      end
    end
  end

  def caveats
    <<~EOS
      Finish setup:
        wut setup          # pick harness + default mode
        wut install-hook   # wire the shell hook into your rc file
        wut doctor         # sanity-check the config

      Or, if you prefer to print the hook snippet and source it yourself:
        eval "$(wut init zsh)"    # bash / fish also supported
    EOS
  end

  test do
    system "#{bin}/wut", "version"
  end
end
