# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wut < Formula
  desc "Route accidental natural-language shell input to your AI harness"
  homepage "https://github.com/sonyaihub/wut"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sonyaihub/wut/releases/download/v0.5.0/wut_Darwin_x86_64.tar.gz"
      sha256 "d8547a3154f7a7ce55dce630cb83dd73315957a9c7811596aa18bc739ea806ed"

      define_method(:install) do
        bin.install "wut"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sonyaihub/wut/releases/download/v0.5.0/wut_Darwin_arm64.tar.gz"
      sha256 "fa478466f718876f4aa83e1dccfe81e5d353cae83365cc9c9e4d332ac8b0a554"

      define_method(:install) do
        bin.install "wut"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyaihub/wut/releases/download/v0.5.0/wut_Linux_x86_64.tar.gz"
      sha256 "2d620c06332739e8949c3f7f1ddab5ade55607ccc1c4b5f28a3a9894d3088ded"
      define_method(:install) do
        bin.install "wut"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonyaihub/wut/releases/download/v0.5.0/wut_Linux_arm64.tar.gz"
      sha256 "5e28b0ecd8ee8e44878f5b07508837e485a28cd062a27c2afcaa85d632051eaa"
      define_method(:install) do
        bin.install "wut"
      end
    end
  end

  test do
    system "#{bin}/wut", "version"
  end
end
